### ISSUE TITLE
When I click download button the app closes

### ISSUE THREAD

**Issue by iShiro007** [captain-nemo1/MusicPlayer#1]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nemocorp.nemoplayer, PID: 11671
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.nemocorp.nemoplayer.Ytsearch.download(Ytsearch.java:222)
        at com.nemocorp.nemoplayer.ScrapAsync.onPostExecute(Ytsearch.java:536)
        at com.nemocorp.nemoplayer.ScrapAsync.onPostExecute(Ytsearch.java:423)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6977)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)`

**Comment by captain-nemo1** [comment]
Hi, I myself am not using the app anymore. I have been working as a contributor to [https://github.com/uditkarode/AbleMusicPlayer]. Its more updated and has cleaner and better code. But I'll look into this on weekend and hopefully fix it. 
Thanks for pointing it out.

**Comment by iShiro007** [comment]
> Hi, I myself am not using the app anymore. I have been working as a contributor to [https://github.com/uditkarode/AbleMusicPlayer]. Its more updated and has cleaner and better code. But I'll look into this on weekend and hopefully fix it.
> Thanks for pointing it out.

Okey thank you so much

**Comment by captain-nemo1** [comment]
Seems to be an issue in the https://github.com/kotvertolet/youtube-jextractor library that's being used to get downloadable links. I have opened an issue there. Let's wait for him to resolve it.

**Comment by iShiro007** [comment]
> Seems to be an issue in the https://github.com/kotvertolet/youtube-jextractor library that's being used to get downloadable links. I have opened an issue there. Let's wait for him to resolve it.

Ok, if there are any updates please let me know by replying to this post.
